eleve/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateur.urls')),
    path('programme/', include('programme.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programme/urls.py
from django.urls import path
from programme.views import *

app_name = "programmes"

urlpatterns = [
    path('', NiveauListviews.as_view(), name="niveaulist"),
    path('<slug:slug>', MatiereListView.as_view(), name="matierelist"),
    path('<str:niveau>/<slug:slug>', LessonListView.as_view(), name="lessonlist"),
    path('<str:niveau>/<str:slug>/create/>', LessonCreateView.as_view(), name="lessoncreate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>', LessonListViewDetail.as_view(), name="lessonlistdetail"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/update/', LessonUpdateView.as_view(), name="lessonupdate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/delete/', LessonDeleteView.as_view(), name="lessondelete"),
    path('lesson/<slug:niveau>/<slug:matiere>/<slug:slug>/exercice/', ExerciceDetailView.as_view(), name='exercisedetail'),
]

utilisateur/urls.py
from django.urls import path 
from utilisateur.views import acceuil, user_login, user_logout, register

urlpatterns = [
    path('',acceuil, name="acceuil"), 
    path('register', register, name="register"), 
    path('login', user_login, name="login"), 
    path('logout',user_logout, name="logout"), 

]

utilisateur/models.py
from django.db import models
from django.contrib.auth.models import User
import os 

def renomer_image(instance, filename):
    upload_to = 'image/'
    ext = filename.split('.')[-1]
    if instance.user.username:
        filename = "photo_profile/{}.{}".format(intance.user.username, ext)
    return os.path.join(upload_to, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio =models.CharField(max_length=50, blank=True)
    photo_profile = models.ImageField(upload_to=renomer_image, blank=True)

    eleve = 'eleve'
    enseignant = 'enseignant'
    parent = 'parent'

    type_user = [
        (eleve, 'eleve'),(enseignant, 'enseignant'),(parent, 'parent')
    ]

    type_profile = models.CharField(max_length=100, choices=type_user, default=eleve)
    
    def __str__(self):
        return self.user.username

utilisateur/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(UserCreationForm):
    class Meta():
        model = User
        fields=[
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2'
        ]
class ProfileForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = [
            'bio',
            'photo_profile',
            'type_profile'
        ]

utilisateur/views.py
from django.shortcuts import render
from .forms import UserForm, ProfileForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def acceuil(request):
    return render(request, 'utilisateur/index.html')

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user 
            profile.save()
            registered = True
            return HttpResponseRedirect('login')
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form=UserForm()
        profile_form = ProfileForm()

    content = {
        'registered':registered,
        'form1':user_form,
        'form2':profile_form,
        }
    return render(request, 'utilisateur/register.html',content)

def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("l'utilisateur est desactiver")
        else:
            return HttpResponse("soit votre nom ou votre mot de passe est incorrect")
    else:  
        return render(request, 'utilisateur/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

utilisateur/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{ % static 'style.css' % }">
    <style>
      body {
        background-image: url("");
        
         }
    footer.bg-dark {
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      padding: 10px 0;
      background-color: #1a3147;
      color: #fff;
      text-align: center;
    }

footer.bg-dark p {
margin: 0;
} 
    </style>

    <title>ELEVE</title>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-lg   bg-dark rounded-pill">
                <a class="navbar-brand text-white" href="#">ELEVE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                       
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">S'abonner</a>
                        </li>
                        {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'register' %}">s'enregistrer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'login' %}">se connecter</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'logout' %}">Se deconnecter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'programmes:niveaulist' %}">COURS</a>
                        </li>
                        {% endif %}
                        <li class="nav-item active">
                            <a class="nav-link btn btn-success text-white" href="#">Evaluation<span class="sr-only">(current)</span></a>
                      </li>
                      
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link text-white" href="#">{{ request.user.username }}<span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>


        {% block content %}

        {% endblock %}

    </div>



    <footer class="bg-dark  mb-2 mt-5 shadow ">
      <p class="text-center text-white"> 
        Tout droit reserve, developpe par ouedraogofataf26@gmail.com
      </p>
    </footer>






    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>