eleve/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateur.urls')),
    path('programme/', include('programme.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programme/urls.py
from django.urls import path
from programme.views import *

app_name = "programmes"

urlpatterns = [
    path('', NiveauListviews.as_view(), name="niveaulist"),
    path('<slug:slug>', MatiereListView.as_view(), name="matierelist"),
    path('<str:niveau>/<slug:slug>', LessonListView.as_view(), name="lessonlist"),
    path('<str:niveau>/<str:slug>/create/>', LessonCreateView.as_view(), name="lessoncreate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>', LessonListViewDetail.as_view(), name="lessonlistdetail"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/update/', LessonUpdateView.as_view(), name="lessonupdate"),
    path('<str:niveau>/<str:matiere>/<slug:slug>/delete/', LessonDeleteView.as_view(), name="lessondelete"),
    path('lesson/<slug:niveau>/<slug:matiere>/<slug:slug>/exercice/', ExerciceDetailView.as_view(), name='exercisedetail'),
]

programme/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Niveaux(models.Model):
    nom = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField()


    def __str__(self):
        return self.nom
    
 
    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)
        super().save(*args, **kwargs)

class Matiere(models.Model):
    matiere_id = models.CharField(unique=True, max_length=40)
    nom = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    niveau = models.ForeignKey(Niveaux, on_delete=models.CASCADE, related_name='matiere' )
    image = models.ImageField(upload_to='matiere', blank=True)
    description = models.TextField(max_length=500)


    def __str__(self):
        return self.nom
    
 
    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)
        super().save(*args, **kwargs)


class Lesson(models.Model):
    lesson_id = models.CharField(unique=True, max_length=40)
    niveau = models.ForeignKey(Niveaux, on_delete=models.CASCADE)
    creer_par = models.ForeignKey(User, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE, related_name='lesson')
    nom = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)
    position = models.PositiveSmallIntegerField(verbose_name='chapitre no')
    video = models.FileField(upload_to="video", null=True, blank=True, verbose_name="cours en video") 
    fpe = models.FileField(upload_to="FPE", null=True, blank=True, verbose_name="Une image du cours") 
    pdf = models.FileField(upload_to="PDF", null=True, blank=True, verbose_name="Fichier pdf du cours") 
    exercice = models.FileField(upload_to="PDF", null=True, blank=True, verbose_name="Fichier d'exercice d'application") 


    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.nom
    
 
    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("programmes:lessonlist", kwargs={"slug": self.matiere.slug, "niveau":self.niveau.slug})




"""EXERCICES
class Exercice(models.Model):
    exercice_id = models.CharField(unique=True, max_length=40)
    niveau = models.ForeignKey(Niveaux, on_delete=models.CASCADE)
    matiere = models.ForeignKey(Matiere, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='exercices')
    nom = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField(max_length=500)
    fichier = models.FileField(upload_to="exercices", null=True, blank=True, verbose_name="Fichier de l'exercice")

    def __str__(self):
        return self.nom

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nom)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("programmes:exercice_detail", kwargs={
            "niveau_slug": self.niveau.slug,
            "matiere_slug": self.matiere.slug,
            "lesson_slug": self.lesson.slug,
            "slug": self.slug
        })
"""

programme/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from .form import LessonForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404


# Create your views here.

class NiveauListviews(ListView):
    context_object_name = 'niveaux'
    model = Niveaux
    template_name = 'programmes/niveaulist.html'


class MatiereListView(DetailView):
    context_object_name = 'niveau'
    model = Niveaux
    template_name = 'programmes/matierelist.html'

class LessonListView(DetailView):
    context_object_name = 'matiere'
    model = Matiere
    template_name = 'programmes/lessonlist.html'


class LessonListViewDetail(DetailView):
    context_object_name = 'lesson'
    model = Lesson
    template_name = 'programmes/lessonlistdetail.html'


class LessonCreateView(CreateView):
    form_class = LessonForm
    context_object_name = 'matiere'
    model = Matiere
    template_name = 'programmes/lessoncreate.html'

    def get_success_url(self):
        self.object = self.get_object()
        niveau = self.object.niveau
        return reverse_lazy('programmes:lessonlist', kwargs={'niveau':niveau, 'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object =self.get_object()
        ls = form.save(commit=False)
        ls.creer_par = self.request.user
        ls.niveau = self.object.niveau
        ls.matiere = self.object
        ls.save()
        return HttpResponseRedirect(self.get_success_url()) 
    

class LessonUpdateView(UpdateView):
    model = Lesson
    fields = ['position','nom', 'pdf', 'fpe','video','exercice']
    context_object_name = 'lesson'
    template_name = 'programmes/lessonupdate.html'



class LessonDeleteView(DeleteView):
    model = Lesson
    context_object_name = "lesson"
    template_name = 'programmes/lessondelete.html'


    def get_success_url(self):
        niveau = self.object.niveau
        matiere = self.object.matiere
        return reverse_lazy("programmes:lessonlist", kwargs={'niveau':niveau, 'slug':matiere.slug} )
        
#exercice



class ExerciceDetailView(DetailView):
    model = Lesson
    template_name = 'programmes/exercisedetail.html'
    context_object_name = 'lesson'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Ajoutez d'autres contextes si nécessaire
        return context

programme/templates/programmes/all_exercices.html
{% extends "base.html" %}

{% block content %}
    <title>Tous les Exercices</title>
</head>
<body>
    <h1>Liste de tous les exercices</h1>
    <ul>
        {% for exercice in exercices %}
            <li>
                <a href="{{ exercice.fichier.url }}">Télécharger l'exercice</a>        
            </li>
        {% endfor %}
    </ul>
</body>

{% endblock %}

programme/templates/programmes/exercice_detail.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ exercice.nom }}</h2>
  <p>{{ exercice.description }}</p>
  {% if exercice.fichier %}
    <a href="{{ exercice.fichier.url }}">Télécharger l'exercice</a>
  {% endif %}
{% endblock %}

programme/templates/programmes/exercice_list.html
{% extends "base.html" %}

{% block content %}
  <h2>Exercices pour {{ lesson.nom }}</h2>
  <ul>
    {% for exercice in exercices %}
      <li><a href="{% url 'programmes:exercice_detail' exercice.niveau.slug exercice.matiere.slug exercice.lesson.slug exercice.slug %}">{{ exercice.nom }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

programme/templates/programmes/lessoncreate.html
{% extends 'base.html' %}

{% block content %}
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Ajouter">

    </form> 
    
{% endblock %}

programme/templates/programmes/lessondelete.html
{% extends 'base.html' %}

{% block content %}
<h1>Etes vous sur de vouloir supprimer</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="supprimer">
    </form> 
    <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=lesson.matiere.slug niveau=lesson.niveau.slug %}" a>annuler la suppression</a>
{% endblock %}

programme/templates/programmes/lessonlist.html
{% extends 'base.html' %}


{% block content %}

<div class="d-flex justify-content-between align-items-center mb-2 text-center">
  <h1 class="ml-5  ">{{ matiere.nom }}</h1>
    <button type="button" class="btn btn-success btn-lg custom-button mr-3">
      <a class="text-white " href="{% url 'programmes:lessoncreate' niveau=matiere.niveau.slug slug=matiere.slug %}">Ajouter un cours</a>
    </button>
  </div>
  
<div class="container-fluid">
  <div class="row">
    {% if user.is_authenticated %}
      {% for lesson in matiere.lesson.all %}
        <div class="col-lg-4 mb-4">
          <div class="card shadow border border-dark" style="width: 18rem;">
            <div class="card-body">
              <strong><h5 class="card-title">Chapitre-{{ lesson.position }} {{ lesson.nom }}</h5></strong>
              <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=matiere.slug niveau=matiere.niveau.slug %}" class="btn btn-primary">Voir le cours</a>
              <p class="card-text">Ajouté par {{ lesson.creer_par }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div class="col-12">
        <p>Pour suivre les cours, il faut se connecter. <a href="{% url 'login' %}">Se connecter</a></p>
      </div>
    {% endif %}
  </div>
</div>


{% endblock %}

programme/templates/programmes/lessonupdate.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="CONFIRMER LA MODIFICATION">
    </form> 
    <a href="{% url 'programmes:lessonlistdetail' slug=lesson.slug matiere=lesson.matiere.slug niveau=lesson.niveau.slug %}" a>annuler la modification</a>
{% endblock %}

programme/templates/programmes/matierelist.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <h1 class="mb-4 text-center">Les Matieres</h1>
    <div class="row justify-content-center">
        {% for matiere in niveau.matiere.all %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ matiere.nom }}</h5>
                    <a href="{% url 'programmes:lessonlist' slug=matiere.slug niveau=niveau.slug %}" class="btn btn-success btn-lg">Accéder</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

programme/templates/programmes/niveaulist.html
{% extends 'base.html' %}

{% block content %}

<h2 class="mb-4 text-center"> Niveu d'Etude  </h2>
<div class="container">
    <div class="row">
        {% for niveau in niveaux %}
            <div class="col-md-3 mb-4 d-flex align-items-stretch">
                <div class="card w-100">
                    <div class="card-body">
                        <h5 class="card-title">{{ niveau.nom }}</h5>
                        <a href="{% url 'programmes:matierelist' slug=niveau.slug %}" class="btn btn-success">Acceder</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>






{% endblock %}